namespace: dev

configmap:
  
  nginx:
    name: nginx-config

Deployment:
  imagePullPolicy: IfNotPresent
  replicasCount: 1

  nginx:
    name: nginx
    image: nginx
    port: 9090

services:

  nginx:
    type: LoadBalancer
    ports: 9090
    targetPort: 9090
    name: nginx-service
    app: nginx
    protocol: TCP
