apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }} #dev
data:
  nginx.conf: |
    server {
      listen 9090;

      location / {
          root /usr/share/nginx/html;
          index index.html;
      }
      location /api/v1/movies {
        proxy_pass http://movie-service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast-db-service:8000/api/v1/casts;
      }
    }
