kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.services.nginx.name }} #nginx-service
  namespace: {{ .Values.namespace }} #dev
spec: 
  selector:
    app:  {{ .Values.services.nginx.app }} #nginx
  type:  {{ .Values.services.nginx.type }} #LoadBalancer 
  ports:
  - name:  nginx-loadbalancer
    port: {{ .Values.services.nginx.ports }} #9090
    protocol: {{ .Values.services.nginx.protocol }} #TCP
    targetPort:  {{ .Values.services.nginx.ports }} #9090